# Jekyll Defaults
title: Seaw Wei Tan
description: A blog about big data technology and machine learning
baseurl: "" # the subpath of your site, e.g. /blog

url: "https://xw0927.github.io"
github: https://github.com/xw0927
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
